Feat/note
LenokSam/Diplom-project pull request #10
Opened 2021-12-07 11:45 UTC by LenokSam

2021-12-07 21:06 UTC, aleksey-drozdov requested changes

2021-12-07 21:06 UTC, aleksey-drozdov commented on src/assets/styles/sections/_note.scss
> +    background-image: url(../../assets/images/note/note.png);
путь лучше заменить на /assets/images/note/note.png

2021-12-07 21:06 UTC, aleksey-drozdov commented on src/assets/styles/util/_var.scss
> +$backNoteLink: #7E0707;
этот красный цвет уже задавался кучу раз

2021-12-07 21:06 UTC, aleksey-drozdov commented on src/assets/styles/util/_var.scss
> +$NoteLink: #FFFFFF;
белый аналогично много раз уже задан. лучше переменные делать не под элемент, а просто обозвать $c-white  и применять там, где нужно.

2021-12-08 08:56 UTC, LenokSam commented on src/assets/styles/util/_var.scss
> +$NoteLink: #FFFFFF;
Изменила переменные  для секции этой пока что, потом в каждой отдельно менять буду

2021-12-08 09:09 UTC, aleksey-drozdov approved these changes

2021-12-08 09:16 UTC, merged